### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by remotesyssupport** [gombadi/aws-tools#1]
Am getting a stream of errors"
# github.com/gombadi/aws-tools

/usr/lib/go/src/github.com/gombadi/aws-tools/ami-cleanup.go:66: cannot use aws.Config literal (type *aws.Config) as type client.ConfigProvider in argument to ec2.New:
        *aws.Config does not implement client.ConfigProvider (missing ClientConfig method)
/usr/lib/go/src/github.com/gombadi/aws-tools/asgservers.go:58: cannot use aws.Config literal (type *aws.Config) as type client.ConfigProvider in argument to autoscaling.New:
        *aws.Config does not implement client.ConfigProvider (missing ClientConfig method)
/usr/lib/go/src/github.com/gombadi/aws-tools/asgservers.go:102: cannot use aws.Config literal (type *aws.Config) as type client.ConfigProvider in argument to ec2.New:
        *aws.Config does not implement client.ConfigProvider (missing ClientConfig method)
/usr/lib/go/src/github.com/gombadi/aws-tools/audit.go:84: cannot use aws.Config literal (type *aws.Config) as type client.ConfigProvider in argument to ec2.New:
        *aws.Config does not implement client.ConfigProvider (missing ClientConfig method)
/usr/lib/go/src/github.com/gombadi/aws-tools/audit.go:117: cannot use aws.Config literal (type *aws.Config) as type client.ConfigProvider in argument to iam.New:
        *aws.Config does not implement client.ConfigProvider (missing ClientConfig method)
/usr/lib/go/src/github.com/gombadi/aws-tools/audit.go:191: cannot use aws.Config literal (type *aws.Config) as type client.ConfigProvider in argument to ec2.New:
        *aws.Config does not implement client.ConfigProvider (missing ClientConfig method)
/usr/lib/go/src/github.com/gombadi/aws-tools/autostop.go:55: cannot use aws.Config literal (type *aws.Config) as type client.ConfigProvider in argument to ec2.New:
        *aws.Config does not implement client.ConfigProvider (missing ClientConfig method)
/usr/lib/go/src/github.com/gombadi/aws-tools/iamssl.go:60: cannot use aws.Config literal (type *aws.Config) as type client.ConfigProvider in argument to iam.New:
        *aws.Config does not implement client.ConfigProvider (missing ClientConfig method)
/usr/lib/go/src/github.com/gombadi/aws-tools/reserved-report.go:80: cannot use aws.Config literal (type *aws.Config) as type client.ConfigProvider in argument to ec2.New:
        *aws.Config does not implement client.ConfigProvider (missing ClientConfig method)
/usr/lib/go/src/github.com/gombadi/aws-tools/reserved-report.go:92: cannot use aws.Config literal (type *aws.Config) as type client.ConfigProvider in argument to rds.New:
        *aws.Config does not implement client.ConfigProvider (missing ClientConfig method)
/usr/lib/go/src/github.com/gombadi/aws-tools/reserved-report.go:92: too many errors

**Comment by gombadi** [comment]
Hi

Thanks for the report.

What version of Go are you using? The repo needs at least Go 1.5 or higher as it uses the vendor directory for dependencies. Do you have GO15VENDOREXPERIMENT=1 in your environment?

From the errors it looks like it is finding a different version of the AWS library.

I tried a clean clone from github.com and did find an error. I missed out a library. If you use this go get command it should install the necessary library -

`go get golang.org/x/crypto/ssh/terminal`

After I installed this library I was able to go build without any errors.

In the next week or so I will update this repo to use the stable v1.0.0 AWS SDK and fix the missing library from the vendor directory.

Regards.

**Comment by remotesyssupport** [comment]
Thank you for the prompt response. Here is my go environment

go version
`go version go1.5 linux/amd64`

go env

``` GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/usr/share/go"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```

I will try what you have suggest and provide inputs.

**Comment by gombadi** [comment]
Codebase has been updated to latest AWS SDK version and dependencies fixed
